domain_path: C:\Users\wewanchu\School\ECE315\lab1\ECE315lab1\lab1\export\lab1\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
